crucrunchbase:
  url: "https://api.crunchbase.com/v3.1/organizations/"
  api.key: "put_api_key_here"
    
company:
  list: "Desktop/crunchbase/process_company_list.csv"
  
db:
  url: "jdbc:postgresql://localhost:5432/crunchbase"
  driverName: "org.postgresql.Driver"
  user: "postgres"
  pass: "admin"
  table: "cb_news"
  