crunchbase:
  url: "https://api.crunchbase.com/v3.1/organizations/"
  api:
    key: "overridden_at_runtime"
    
company:
  list: "Desktop/crunchbase/process_company_list_enormous.csv"
  
db:
  url: "jdbc:postgresql://localhost:5432/crunchbase"
  driverName: "org.postgresql.Driver"
  user: "postgres"
  pass: "admin"
  table: "cb_news"
  